base:
  project: big-mart-sales
  random_state: 42
  target_col: Item_Outlet_Sales

data_source:
  raw_data: ../data_raw/bigmart.csv

load_data:
  raw_dataset_csv: ../data/raw/bigmart.csv

split_data:
  train_path: ../data/processed/train_bigmart.csv
  test_path: ../data/processed/test_bigmart.csv
  test_size: 0.2

estimators:
  RandomForest:
    params:
      n_estimators: [100,250,450,700,900]
      # Number of features to consider at every split
      max_features: ['auto', 'sqrt']
      # Maximum number of levels in tree
      max_depth: [5, 10, 15, 20, 25, 30]
      # Minimum number of samples required to split a node
      min_samples_split: [2, 5, 10, 15, 100]
      # Minimum number of samples required at each leaf node
      min_samples_leaf: [1, 2, 5, 10]

model_dir: ../saved_models

reports:
  params: ../report/params.json
  scores: ../report/scores.json

predict_model_dir: predict_service/model