stages:
  load_data:
    cmd: python3 load_data.py --config=../params.yaml
    deps:
    - get_data.py
    - load_data.py
    - ../data_raw/bigmart.csv
    outs:
    - ../data/raw/bigmart.csv

  split_data:
    cmd: python3 split_data.py --config=../params.yaml
    deps:
    - split_data.py
    - ../data/raw/bigmart.csv
    outs:
    - ../data/processed/train_bigmart.csv
    - ../data/processed/test_bigmart.csv

  train_evaluate:
    cmd: python3 train_evaluate.py --config=../params.yaml
    deps:
    - ../data/processed/train_bigmart.csv
    - ../data/processed/test_bigmart.csv
    - train_evaluate.py
    metrics:
    - ../report/params.json:
          cache: false
    - ../report/scores.json:
          cache: false
    outs:
    - ../saved_models/label_encode.pkl
    - ../saved_models/rf_model.pkl
    - ../saved_models/standard_scaler.pkl 